# backend/app/api/upload.py

from fastapi import APIRouter, UploadFile, File, Form, HTTPException, BackgroundTasks
from typing import Optional
import uuid
from core.supabase_client import supabase
from services.ocr_asr_service import ocr_asr_service
from services.file_service import file_service
from services.memory_service import memory_service
from utils.validators import validators
from utils.logger import logger
from utils.exceptions import OCRException, ASRException, ValidationException
from pydantic import BaseModel

router = APIRouter(prefix="/upload", tags=["Upload"])

class UploadResponse(BaseModel):
    session_id: str
    status: str  # "processing", "completed", "error"
    media_url: Optional[str] = None
    media_type: str  # "image", "audio", "text"
    extracted_text: Optional[str] = None
    confidence: float = 0.0
    needs_review: bool = True
    error: Optional[str] = None

class TextUploadRequest(BaseModel):
    text: str

async def process_upload_background(
    session_id: str,
    file_bytes: bytes,
    filename: str,
    content_type: str
):
    """Background task for processing uploads asynchronously"""
    try:
        logger.info(f"[Background] Processing upload for session: {session_id}")
        
        # Upload file to storage
        upload_result = await file_service.upload_file(
            file_bytes=file_bytes,
            filename=filename,
            content_type=content_type,
            session_id=session_id
        )
        
        if not upload_result["success"]:
            raise Exception(upload_result["error"])
        
        media_url = upload_result["url"]
        media_type = upload_result["media_type"]
        
        # Process based on media type
        if media_type == "image":
            ocr_result = await ocr_asr_service.process_image(file_bytes, filename)
            extracted_text = ocr_result["extracted_text"]
            confidence = ocr_result["confidence"]
            needs_review = ocr_result["needs_review"]
            
            if not ocr_result["success"]:
                raise OCRException(ocr_result["error"])
                
        elif media_type == "audio":
            asr_result = await ocr_asr_service.process_audio(file_bytes, filename)
            extracted_text = asr_result["extracted_text"]
            confidence = asr_result["confidence"]
            needs_review = asr_result["needs_review"]
            
            if not asr_result["success"]:
                raise ASRException(asr_result["error"])
        else:
            extracted_text = ""
            confidence = 0.0
            needs_review = True
        
        # Create session in Supabase
        session_data = {
            "id": session_id,
            "user_input": extracted_text,
            "media_url": media_url,
            "media_type": media_type,
            "ocr_text": extracted_text,
            "hitl_status": "pending" if needs_review else "approved",
            "created_at": None,  # Auto-generated by DB
            "updated_at": None
        }
        
        supabase.table("sessions").insert(session_data).execute()
        
        # Cache session
        memory_service.cache_session(session_id, {
            "session_id": session_id,
            "extracted_text": extracted_text,
            "media_url": media_url,
            "media_type": media_type,
            "confidence": confidence,
            "needs_review": needs_review,
            "status": "completed"
        })
        
        logger.info(f"[Background] Upload processing complete for session: {session_id}")
        
    except Exception as e:
        logger.error(f"[Background] Upload processing failed: {str(e)}")
        # Update session with error
        supabase.table("sessions").update({
            "hitl_status": "error",
            "hitl_feedback": str(e)
        }).eq("id", session_id).execute()

@router.post("/image", response_model=UploadResponse)
async def upload_image(
    file: UploadFile = File(...),
    background_tasks: BackgroundTasks = None
):
    """
    Upload image for OCR processing.
    Returns session_id immediately, processing happens in background.
    """
    try:
        # Validate file type
        is_valid, error = validators.validate_file_type(file.content_type)
        if not is_valid:
            raise ValidationException(error)
        
        # Generate session ID
        session_id = str(uuid.uuid4())
        
        # Read file bytes
        file_bytes = await file.read()
        
        # Start background processing
        if background_tasks:
            background_tasks.add_task(
                process_upload_background,
                session_id,
                file_bytes,
                file.filename or "image.jpg",
                file.content_type
            )
        
        # Return immediate response (processing in background)
        return UploadResponse(
            session_id=session_id,
            status="processing",
            media_url=None,
            media_type="image",
            extracted_text=None,
            confidence=0.0,
            needs_review=True,
            error=None
        )
        
    except ValidationException as e:
        raise HTTPException(status_code=400, detail=e.message)
    except Exception as e:
        logger.error(f"Image upload error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/audio", response_model=UploadResponse)
async def upload_audio(
    file: UploadFile = File(...),
    background_tasks: BackgroundTasks = None
):
    """
    Upload audio for ASR transcription.
    Returns session_id immediately, processing happens in background.
    """
    try:
        # Validate file type
        is_valid, error = validators.validate_file_type(file.content_type)
        if not is_valid:
            raise ValidationException(error)
        
        # Generate session ID
        session_id = str(uuid.uuid4())
        
        # Read file bytes
        file_bytes = await file.read()
        
        # Start background processing
        if background_tasks:
            background_tasks.add_task(
                process_upload_background,
                session_id,
                file_bytes,
                file.filename or "audio.mp3",
                file.content_type
            )
        
        # Return immediate response (processing in background)
        return UploadResponse(
            session_id=session_id,
            status="processing",
            media_url=None,
            media_type="audio",
            extracted_text=None,
            confidence=0.0,
            needs_review=True,
            error=None
        )
        
    except ValidationException as e:
        raise HTTPException(status_code=400, detail=e.message)
    except Exception as e:
        logger.error(f"Audio upload error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/text", response_model=UploadResponse)
async def upload_text(request: TextUploadRequest):
    """
    Submit text input directly (no OCR/ASR needed).
    """
    try:
        # Validate text
        is_valid, error = validators.validate_math_text(request.text)
        if not is_valid:
            raise ValidationException(error)
        
        # Generate session ID
        session_id = str(uuid.uuid4())
        
        # Create session in Supabase (text doesn't need background processing)
        session_data = {
            "id": session_id,
            "user_input": request.text,
            "media_url": None,
            "media_type": "text",
            "ocr_text": request.text,
            "hitl_status": "approved",  # Text input doesn't need OCR review
            "created_at": None,
            "updated_at": None
        }
        
        supabase.table("sessions").insert(session_data).execute()
        
        # Cache session
        memory_service.cache_session(session_id, {
            "session_id": session_id,
            "extracted_text": request.text,
            "media_url": None,
            "media_type": "text",
            "confidence": 1.0,
            "needs_review": False,
            "status": "completed"
        })
        
        return UploadResponse(
            session_id=session_id,
            status="completed",
            media_url=None,
            media_type="text",
            extracted_text=request.text,
            confidence=1.0,
            needs_review=False,
            error=None
        )
        
    except ValidationException as e:
        raise HTTPException(status_code=400, detail=e.message)
    except Exception as e:
        logger.error(f"Text upload error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/{session_id}", response_model=UploadResponse)
async def get_upload_status(session_id: str):
    """
    Check status of upload processing (for polling).
    """
    try:
        # Validate session ID
        is_valid, error = validators.validate_session_id(session_id)
        if not is_valid:
            raise ValidationException(error)
        
        # Check cache first
        cached = memory_service.get_cached_session(session_id)
        if cached:
            return UploadResponse(
                session_id=session_id,
                status=cached.get("status", "processing"),
                media_url=cached.get("media_url"),
                media_type=cached.get("media_type", "text"),
                extracted_text=cached.get("extracted_text"),
                confidence=cached.get("confidence", 0.0),
                needs_review=cached.get("needs_review", True),
                error=None
            )
        
        # Query Supabase
        response = supabase.table("sessions").select("*").eq("id", session_id).execute()
        
        if not response.data or len(response.data) == 0:
            raise HTTPException(status_code=404, detail="Session not found")
        
        row = response.data[0]
        
        return UploadResponse(
            session_id=session_id,
            status="completed" if row.get("ocr_text") else "processing",
            media_url=row.get("media_url"),
            media_type=row.get("media_type", "text"),
            extracted_text=row.get("ocr_text") or row.get("user_input"),
            confidence=1.0 if row.get("media_type") == "text" else 0.7,
            needs_review=row.get("hitl_status") == "pending",
            error=row.get("hitl_feedback")
        )
        
    except ValidationException as e:
        raise HTTPException(status_code=400, detail=e.message)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Upload status check error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))